services:
    twig-twm:
        # Basic starting info
        container_name: twig-twm
        image: nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04
        network_mode: "host"

        # Set up workspace
        working_dir: /workspace
        volumes:
            - ./jobs/:/workspace/jobs
            - ./src/:/workspace/src
            - ./install/:/workspace/install

        # Enable nvidia https://docs.docker.com/compose/gpu-support/
        deploy: 
            resources: 
                reservations: 
                    devices: 
                        - capabilities: [gpu]
        
        # Install TWIG
        command: bash -c "install/install.sh &> install/docker_up.log && tail -F /dev/null"
